doc/install.rst

Updated documentation and added information on how to install pyoidc in a windows environment

Install script for windows

---

setup.py
src/oic/utils/clientdb.py
tests/test_clientdb.py

Added MDX interface.

---

src/oic/utils/client_management.py

Added support for jwks_uri to the client_management script

Added support for jwks_uri to the client_management script

---

src/oic/utils/sdb.py

Changed so it works even with non-dict Databases

Updated SessionDB.update

---

oidc_example/op2/config.py.full
oidc_example/op2/config.py.simple
oidc_example/op2/server.py
oidc_example/rp3/conf.py.example
oidc_example/rp3/rp3.py

Allow the port and baseurl to be specified as command line args for rp3 and op2.

Configure with commandline args

---

src/oic/oauth2/__init__.py
src/oic/utils/authn/client.py

client_id is only part of the token request if authn_method='client_secret_post'.
Fetch it properly from the 'client_assertion' in the request in case of authn_method='client_secret_jwt'/'private_key_jwt' or from the HTTP Basic Auth header in case of authn_method='client_secret_basic'.

Don't rely on client_id existing in request.

---

src/oic/oic/provider.py
src/oic/utils/userinfo/__init__.py

uic dict is now trimmed in id_token as well

Authz tunning part 2

---

src/oic/oic/provider.py
tests/oic/oic/test_oic_provider.py

Make it possible for subclasses to add or remove checks for redirect_uris.

Refactored oic.Provider for easier subclassing.

---

src/oic/oauth2/provider.py
src/oic/oic/provider.py

Endpoint class simplified.
Removed unused methods and added url parameter.
Endpoint matching is done by etype and url construction by url parameter. This allows overrides on url creation.

Endpoint refactor

---

src/oic/utils/shelve_wrapper.py
tests/test_shelve_wrapper.py

Fixes nasty bug only apparent on Ubuntu.

Don't inherit Shelf since we're not supporting sync properly.

---

doc/howto/rp.rst

Some typos I encountered when reading the RP cookbook

fix typos in RP cookbook

---

src/oic/oauth2/provider.py
src/oic/oic/provider.py

Make sure we pass client_id as string to cdb, not unicode

---

setup.py
src/oic/utils/__init__.py
src/oic/utils/keyio.py
tests/test_keyio.py

Includes unicode fixes after updates in pyjwkest.

Only include public attributes of JWK in JWKS.

---

src/oic/oic/provider.py
tests/test_oic_provider.py

Return error response if token is missing or malformed on userinfo
endpoint

UserInfo token error

---

src/oic/oic/provider.py
tests/test_oic_provider.py

Instead return error response with invalid_request

Remove assert on read_registration

---

src/oic/oic/provider.py

Fix unquote on access_token endpoint as well

---

.travis.yml
src/oic/extension/signed_http_req.py
tests/test_signed_http_request.py

Fixes the sometimes broken tests on Travis due to a non-deterministic implementation.

Signed http req fix

---

doc/howto/rp.rst

* Fixed a bunch of grammatical errors
* Fixed the reference to `rndstr` in the examples

Lots of small fixes

---

doc/howto/rp.rst

Screwed up the links

---

doc/howto/rp.rst

This may be what is preventing updates to readthedocs.

Fixed the links and a bullet error

---

src/oic/utils/userinfo/ldap_info.py

1. Implement tls constructor parameter.
2. Add additional constructor parameter, attrmap, that defaults to OPENID2LDAP module dictionary.

Issue #192 UserInfoLDAP enhancements.

---

oidc_fed/oidcfed.txt
oidc_fed/oidcfed.xml

openid-connect-federation-1_0-00 as adopted by the OpenID Connect Working Group

Created openid-connect-federation-1_0-00

---

src/oic/oic/__init__.py

As per [RFC7231](https://tools.ietf.org/html/rfc7231.html) the URL in Location header can be relative. Consumer should accomodate for that.

Fix provider_config redirect with relative URL

---

src/oic/utils/http_util.py
tests/test_http_util.py
tests/test_requirements.txt

Escape message in Response

---

README.rst

Add link to specification and documentation.

---

.gitignore

Whilst running `tox`, I saw these new files.

Add tox generated files to `.gitignore`.

---

src/oic/utils/webfinger.py
tests/test_webfinger.py

A more general solution to the webfinger problem described by Hans in #272.

Modified webfinger to allow non-standard arguments.

---

CHANGELOG.md

Add change log.

---

CHANGELOG.md
Makefile
doc/contrib/install.rst
requirements.txt
requirements/admin.in
requirements/admin.txt
requirements/base.in
requirements/base.txt
requirements/test.in
requirements/test.txt

So, this PR adds the following two Make targets:
```
$ make install  # install all python dependencies
$ make upgrade  # upgrade all python dependencies
```
Please see http://nvie.com/posts/pin-your-packages/ and https://github.com/jazzband/pip-tools to get up to speed on why this important and what `pip-tools` does.

Add pip-tools for dependency management.

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py

> I am not sure if the assert for error should be access_denied or bad_code. Leaving that up to you...
@tpazderka, I went with the same error as a state mismatch so as not to leak any extra context.
@rohe, can we please use this as an excuse to follow up on https://github.com/OpenIDC/pyoidc/issues/264? I don't mind doing it, so if you don't have time, please give me permission on pypi. This package needs a new release, and will most likely need regular minor release for various bug fixes.

Follow on from #284/5 - Deal with missing code

---

requirements/base.txt
requirements/test.txt

Let's try and stay up to date here :)

Bump dependencies

---

.travis.yml
Makefile
requirements/test.in
requirements/test.txt
tox.ini

Hacking on something for https://github.com/OpenIDC/pyoidc/issues/301.

Rely solely on Tox for environment testing.

---

tox.ini

Reduce duplication for Tox testing.

---

src/oic/extension/provider.py
src/oic/extension/token.py
src/oic/oauth2/__init__.py
src/oic/oic/__init__.py
src/oic/oic/provider.py
src/oic/utils/authn/client.py
src/oic/utils/shelve_wrapper.py
src/oic/utils/stateless.py
tests/mitmsrv.py
tests/test_client.py
tests/test_grant.py
tests/test_keyio.py
tests/test_oauth2_message.py
tests/test_oic.py
tests/test_oic_consumer.py
tests/test_oic_message.py

Cleanup imports

---

src/oic/extension/popjwt.py
src/oic/extension/single.py
src/oic/extension/token.py
src/oic/oauth2/__init__.py
src/oic/oauth2/provider.py
src/oic/oauth2/util.py
src/oic/oic/__init__.py
src/oic/oic/claims_provider.py
src/oic/oic/provider.py
src/oic/utils/__init__.py
src/oic/utils/authn/multi_auth.py
src/oic/utils/authn/saml.py
src/oic/utils/restrict.py
src/oic/utils/rp/__init__.py
src/oic/utils/sdb.py
src/oic/utils/userinfo/__init__.py
src/oic/utils/webfinger.py
tests/test_client.py
tests/test_oauth2_consumer.py
tests/test_oic_message.py
tests/test_oic_provider.py
tests/test_pop.py
tests/test_sanitize.py
tests/test_token.py
tests/test_token_handler.py
tests/test_util.py
tests/test_x_client.py

Fixed whitespace related errors

---

src/oic/extension/client.py
src/oic/extension/message.py
src/oic/extension/provider.py
src/oic/oauth2/__init__.py
src/oic/oauth2/message.py
src/oic/oauth2/provider.py
src/oic/oic/__init__.py
src/oic/oic/claims_provider.py
src/oic/oic/message.py
src/oic/oic/provider.py
src/oic/utils/authn/client.py
src/oic/utils/authn/user.py
src/oic/utils/client_management.py
src/oic/utils/keyio.py
src/oic/utils/rp/__init__.py
src/oic/utils/sdb.py
tests/fakeoicsrv.py
tests/mitmsrv.py
tests/test_client.py
tests/test_oauth2.py
tests/test_oic_consumer.py
tests/test_oic_provider.py
tests/test_sdb.py

Removed unused variables

---

CHANGELOG.md

Add note about imports, bump release from minor to major.

---

src/oic/utils/keyio.py
tests/test_keyio.py

Catch Exceptions correctly

---

CHANGELOG.md
src/oic/utils/sanitize.py
tests/test_oauth2_provider.py
tests/test_sanitize.py

Fix sanitize to completely replace strings starting with B or U

---

CHANGELOG.md
src/oic/oic/__init__.py
tests/test_claims.py

---
~~@rohe, you'll have to advise on this one. I was just passing through
here and started to try to figure out what this function is really
doing.~~
OK, I think I've covered this refactoring.

Refactor claims_match.

---

src/oic/oic/provider.py
tests/test_oic_provider.py

Follows from https://github.com/OpenIDC/pyoidc/pull/324#issuecomment-292816200.

Cosmetics - inlining and comment removal.

---

setup.py

Fix package settings.

---

CHANGELOG.md

Makes no sense to have two unreleased sections in there.

Merge unreleased 0.10.0.1 and 0.11.0.0 changelog sections

---

src/oic/oauth2/message.py
tests/test_keyio.py
tests/test_oauth2_message.py

Lines that was not removed when handling conflict.

Removed lines that shouldn't have been there to begin with.

---

CHANGELOG.md
src/oic/oauth2/__init__.py
src/oic/oauth2/message.py
src/oic/oic/__init__.py
src/oic/utils/authn/client.py

Implement Resource Owner Password Credentials Grant correctly

---

CHANGELOG.md
src/oic/exception.py
src/oic/oauth2/grant.py
src/oic/oic/__init__.py

Added check for matching sub in ID Token and Userinfo.

---

setup.py

Closes https://github.com/OpenIDC/pyoidc/issues/394.

Move test deps to `tests_require`

---

CHANGELOG.md
src/oic/oauth2/provider.py
src/oic/utils/http_util.py
tests/test_http_util.py

Allow to set Cookie path and domain

---

CHANGELOG.md
src/oic/utils/sdb.py

SHA224 is as good as HMAC-SHA224 when no validation is performed.
See Issue #392.

Simplify sid construction

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py

Fix generation of endpoint urls

---

CHANGELOG.md
src/oic/oauth2/message.py
tests/test_oauth2_message.py

create test for success and failure conditions for oic profile containing empty lists
add changelog
Closes #411 
---

to_dict method handles empty list case

---

CHANGELOG.md
src/oic/oauth2/message.py
src/oic/oic/message.py
tests/test_oic_message.py

Fixed bug where loading non-boolean worked for something marked as boolean.
Added tests.
---

Made phone_number_verified be boolean.

---

CHANGELOG.md
src/oic/__init__.py
src/oic/utils/http_util.py

From now on we will use X.X.X as structure for release numbers and tags.
- [X ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
---

Release 0.12.0

---

CHANGELOG.md
src/oic/oauth2/provider.py
tests/test_http_util.py
tests/test_oauth2_provider.py

Dealing with issue #399 
Sorry about the extra commits. Just tried to even them out.
- [X ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
---

Response types

---

doc/contrib/install.rst

fix small typo

---

src/oic/oic/__init__.py

see openid-certification/oidctest#38

log the registration request

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py

Fix creation of error on client registration

---

.travis.yml
setup.py
tox.ini

---
- Using matrix only when absolutely neccessary
- Do not use pipenv for installation, it duplicates tox setup and package installation (it looks like it shortens a total runtime by 25%)

Optimize tox and travis

---

.appveyor.yml
README.rst

Add Appveyor support

---

README.rst

Hi folks, I'm starting to get dragged into other projects and I am not actively using pyoidc any more, so I think it is time to remove myself here as I won't get time to maintain here. All the best, I will still lurk the mailing list :)

Remove myself for maintainer listing.

---

README.rst
appveyor.yml

---
Testing if appveyor will build this.

[WIP] test

---

CHANGELOG.md
Pipfile
setup.py
src/oic/oauth2/provider.py
src/oic/utils/client_management.py
src/oic/utils/clientdb.py
tests/test_clientdb.py
tests/test_oic_provider.py

Base implementation of ClientDatabase classes

---

pylama.ini
src/oic/oauth2/message.py
tests/test_oauth2_message.py

Decreasing complexity
Close #464
---

Refactor Message._add_value and Message.from_dict a little bit

---

CHANGELOG.md
src/oic/extension/client.py
src/oic/extension/provider.py
src/oic/oauth2/__init__.py
src/oic/oauth2/message.py
src/oic/oauth2/provider.py
src/oic/oauth2/util.py
src/oic/oic/__init__.py
src/oic/oic/message.py
src/oic/oic/provider.py
src/oic/utils/aes.py
src/oic/utils/authn/client.py
src/oic/utils/keyio.py
src/oic/utils/stateless.py
src/oic/utils/webfinger.py
tests/test_util.py

---
They shouldn't be used for checking some conditions as they can get optimized at runtime.

Replace asserts in code with conditions

---

CHANGELOG.md
doc/examples/op.rst
oidc_example/op2/server.py
oidc_example/op3/server.py
src/oic/oic/provider.py
src/oic/utils/template_render.py
tests/test_oic_provider.py
tests/test_util.py

Add ability to specify custom form_post template

---

CHANGELOG.md
src/oic/extension/provider.py
src/oic/oauth2/__init__.py
src/oic/oauth2/provider.py
src/oic/oic/provider.py
src/oic/utils/http_util.py
tests/test_http_util.py
tests/test_oauth2_provider.py
tests/test_oic_provider.py
tests/test_x_provider.py

Refactor response

---

CHANGELOG.md
src/oic/utils/keyio.py
tests/test_keyio.py

skip keys that are not properly defined

---

CHANGELOG.md
doc/examples/op.rst
src/oic/oic/__init__.py
src/oic/oic/provider.py
tests/test_oic.py
tests/test_oic_provider.py

Add support for extra claims

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py
tests/test_x_provider.py

Fix UserInfo endpoint for deleted clients

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py

Remove duplicate mapping in Client_db

---

src/oic/extension/message.py
src/oic/extension/provider.py
src/oic/oauth2/provider.py
src/oic/oic/message.py
src/oic/utils/authn/user.py

Close #504
---
Still work in progress...

Remove asserts that are used in place of conditions

---

CHANGELOG.md
doc/examples/rp.rst
src/oic/oic/__init__.py
tests/test_oic_consumer.py

Add registration_token kwarg to Client.register

---

CHANGELOG.md
src/oic/oauth2/provider.py
tests/test_oic_provider.py

Fix  verify redirect uri

---

src/oic/oic/__init__.py
tests/test_oic_consumer.py

Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
---

interpret passed in grant_types when assembling the registration request

---

src/oic/oauth2/__init__.py
src/oic/oic/__init__.py

Fix token state and refresh params

---

src/oic/oauth2/base.py
src/oic/oic/__init__.py
src/oic/utils/authn/user.py

Fix quality run

---

doc/contrib/install.rst
doc/examples/docker.rst
doc/index.rst

Fix links in docd

---

src/oic/extension/device_flow.py
src/oic/extension/message.py
src/oic/extension/provider.py
src/oic/oauth2/__init__.py
src/oic/oauth2/base.py
src/oic/oauth2/message.py
src/oic/oauth2/provider.py
src/oic/oic/__init__.py
src/oic/oic/claims_provider.py
src/oic/oic/consumer.py
src/oic/oic/message.py
src/oic/oic/provider.py
src/oic/utils/authn/client.py
src/oic/utils/authn/client_saml.py
src/oic/utils/authn/saml.py
src/oic/utils/authn/user.py
src/oic/utils/rp/__init__.py
src/oic/utils/sdb.py
src/oic/utils/stateless.py
src/oic/utils/time_util.py
src/oic/utils/userinfo/distaggr.py
tests/fakeoicsrv.py
tests/mitmsrv.py
tests/test_oauth2.py
tests/test_oic.py
tests/test_oic_provider.py
tests/test_sdb.py
tests/test_time_util.py
tests/test_token.py

Cleaned commented code

---

tests/test_keyio.py

Fix failing test on expired key

---

src/oic/utils/client_management.py
src/oic/utils/keyio.py
tests/test_keyio.py
tests/test_oic_consumer.py

Close files in code

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py

Fix uncaught error in _verify_sector_identifier

---

.travis.yml
appveyor.yml
setup.py
src/oic/utils/authn/authn_context.py
tox.ini

Mark support for python 3.7

---

CHANGELOG.md
src/oic/oic/message.py
tests/test_oic_message.py

Fix verification of encypted id_token

---

tests/test_oic_provider.py
tests/test_sdb.py

Cleanup pytest warnings

---

CHANGELOG.md
src/oic/oic/message.py
tests/test_oic_message.py

Fix encrypted IdToken 

---

CHANGELOG.md
src/oic/oauth2/provider.py
tests/test_oauth2_provider.py

Do not set cookies that do not belong to us

---

CHANGELOG.md
src/oic/extension/message.py
src/oic/oauth2/message.py
src/oic/oic/message.py
tests/test_oauth2_message.py

Use namedtuple for c_param definitions

---

CHANGELOG.md
src/oic/oic/provider.py
tests/data/keys/jwk_enc.json
tests/test_oic_provider.py

Fixed key recovery process

---

.gitignore
CHANGELOG.md
Makefile
README.rst
setup.py

---
Hi there! We'd like to start contributing to the repo, as we're facing issues getting OP examples working.. So, here's a few commits to address the initial issues I faced when trying to get my development environment up and running yesterday. 😸

More Helpful Getting Started Docs

---

src/oic/extension/client.py
src/oic/extension/provider.py

Cleanup duplicated code in extensions

---

.travis.yml
docker/op_test/Dockerfile
docker/rp_test/Dockerfile

Fix integration tests

---

src/oic/oauth2/__init__.py
src/oic/oic/__init__.py
tests/test_oauth2_consumer.py
tests/test_oic_consumer.py

---
Touch of refactoring...
Removed duplicated methods on Clients.

Refactor client

---

setup.py
src/oic/oauth2/__init__.py

Most of the methods annotated.
---
Part of #630

Annotate Client

---

src/oic/oauth2/__init__.py

Annotate Server

---

src/oic/oauth2/provider.py
src/oic/oic/provider.py

---
Close #629 
I do believe that I got most of that.

Cleaned up more methods

---

CHANGELOG.md
src/oic/extension/provider.py
tests/test_x_provider.py

Fix ROPC in extensions

---

CHANGELOG.md
src/oic/oic/provider.py

Use more secure random generator in client_secret

---

CHANGELOG.md
src/oic/oic/provider.py
tests/test_oic_provider.py

Re-add symmetric keys if issuer keys are missing

---

CHANGELOG.md
src/oic/extension/client.py
src/oic/extension/message.py
src/oic/extension/provider.py
src/oic/oauth2/__init__.py
src/oic/oauth2/message.py
src/oic/oauth2/provider.py
src/oic/oic/__init__.py
src/oic/oic/message.py
src/oic/oic/provider.py
src/oic/utils/rp/__init__.py
src/oic/utils/rp/oauth2.py
tests/test_oauth2_message.py
tests/test_x_dynreg.py

Message factory

---

CHANGELOG.md
src/oic/oic/__init__.py
src/oic/utils/webfinger.py
tests/test_webfinger.py

Allow webfinger search on forced host

---

docker/integration_tests/Dockerfile
docker/op/Dockerfile
docker/op_test/Dockerfile
docker/rp_test/Dockerfile

---
Reorganized the docker file in order to minimize diffs and builds.
Hopefully close #651.

Integration tests

---

CHANGELOG.md
src/oic/extension/message.py
src/oic/extension/provider.py
src/oic/oauth2/message.py
src/oic/oauth2/provider.py
src/oic/oic/provider.py
tests/test_oauth2_provider.py
tests/test_oic_provider.py

Moved provider_info_endpoint from extensions to oauth

---

docker/integration_tests/Dockerfile
docker/op/Dockerfile
docker/op/run.sh

Update integration tests

---

src/oic/utils/keyio.py
tests/test_keyio.py

Fix check_key_availability for jwks keys

---

CHANGELOG.md
src/oic/oauth2/message.py
src/oic/oic/message.py
tests/test_oic_message.py

- [ X] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ X] New code is annotated.
- [ X] Changes are covered by tests.
---
The messages needed to implement Single-Sign-Out according to:
- https://openid.net/specs/openid-connect-backchannel-1_0.html,
- https://openid.net/specs/openid-connect-frontchannel-1_0.html and 
- https://openid.net/specs/openid-connect-session-1_0.html

Logout message

---

CHANGELOG.md
src/oic/extension/token.py
src/oic/utils/sdb.py
src/oic/utils/token_handler.py
tests/test_oic_provider.py
tests/test_token.py
tests/test_x_provider.py

Updated all code to work with refresh_token_factory
Close #644
---

Deprecated RefreshDB

---

CHANGELOG.md
MANIFEST.in
setup.py

Fix PEP561 compliance

---

.travis.yml
CHANGELOG.md

---
We should probably have a look at some linter for markdown so this doesn't happen again...

Fix reference in Changelog

---

CHANGELOG.md
src/oic/oic/provider.py
src/oic/utils/authn/client.py
src/oic/utils/http_util.py

Removed more deprecated code

---

appveyor.yml
tests/test_keyio.py
tox.ini

---
Do not use network in tests at all.

Made network test not connecting

---

CHANGELOG.md
src/oic/oauth2/__init__.py

Fix basic_auth with client password

---

src/oic/utils/userinfo/aa_info.py

Fix quality build

---

tox.ini

Allow proper usage of posargs in tox

---

setup.py

---
Freezing mypy version  for now. The fixes will probably take some time to fix...

Freeze mypy version for now

---

tests/test_oic_provider.py

Ref #685
---
By product of looking into #685, but (almost) every test is a good test :)

Add test for claims in id_token

---

CHANGELOG.md
src/oic/oic/__init__.py
src/oic/oic/provider.py
tests/test_oauth2_consumer.py
tests/test_oauth2_provider.py
tests/test_oic_consumer_logout.py
tests/test_oic_provider.py
tests/test_oic_provider_logout.py
tests/test_sdb.py
tests/test_token.py
tests/test_x_provider.py

The provider side of handling logout

---

src/oic/oic/provider.py
tests/test_keyio.py
tests/test_oic_provider_logout.py

---
A new version of Black changes some small stuff. Updated.

Run new black

---

.travis.yml
tox.ini

Test under python 3.8 in travis and appveyor

---

README.rst
setup.py
tox.ini

---
`command` is not supported on PyPi, so it won't upload...
We might want to add a check as well...

Fix readme

---

docker/integration_tests/Dockerfile
docker/integration_tests/run.sh

Run integration tests in parallel

---

doc/contrib/documentation.rst
doc/contrib/testing.rst
doc/examples/rp.rst
src/oic/utils/settings.py

Fix docs about manual provider info

---

tox.ini

Close #713
---
Depends on #707 and it will fail until the last issue is fixed.

Add bandit tests to CI

---

setup.py
tox.ini

Fix twine warnings, silence sdist in quality

---

docker/op/Dockerfile
docker/op/run.sh

Update certification test

---

CHANGELOG.md
src/oic/oauth2/__init__.py
tests/test_oauth2.py

Fix Oauth flow for client with Client Credentials

---

CHANGELOG.md
src/oic/oauth2/__init__.py
src/oic/oauth2/message.py
tests/test_oauth2.py

Close #728
Due to code overlap, I have implemented this on top of a fix for #727. This can be merged after that.
---

Added ability to use Extension grants in OAuth flow

---

pylama.ini
src/oic/oic/provider.py
src/oic/utils/rp/__init__.py

Touch of refactoring to decrease complexity

---

tests/test_oic.py

Remove fake_request in favor of requests

---

docker/integration_tests/Dockerfile
src/oic/oauth2/__init__.py
src/oic/oauth2/provider.py
src/oic/oic/__init__.py
tests/test_oauth2.py
tests/test_oauth2_message.py
tests/utils/test_client_management_run.py

Fix for black update

---

.github/workflows/python-test.yml
.travis.yml
tox.ini

Try Github actions

---

.travis.yml
docker/integration_tests/Dockerfile
docker/op_test/Dockerfile
docker/rp_test/Dockerfile

Try to upgrade pip to get cryptography .whl working.
---

Upgrade pip in travis

---

.travis.yml

It was getting HTTP 429 code from github.
---

Add delay to link checker

---

doc/examples/rp.rst

Just a few corrections I had noticed reading the documentation.
---

Minor grammatical changes

---

setup.py
src/oic/oauth2/base.py
tox.ini

Fix for a new version of mypy

---

oauth_example/as/as.py
oidc_example/op1/oc_server.py
src/oic/utils/client_management.py
src/oic/utils/shelve_wrapper.py
tox.ini

Re-enable bandit

---

setup.py

Moved from pyldap to python-ldap

---

.github/workflows/python-test.yml
CHANGELOG.md
setup.py
src/oic/utils/settings.py
tox.ini

Added support for python 3.11

---

.github/workflows/python-test.yml

Schedule daily CI run

---

tests/test_oic_provider.py

Fix test for new requests version

---

setup.py
src/oic/oauth2/util.py
src/oic/utils/__init__.py
src/oic/utils/aes.py

Fix typing for Cryptodomex

---

CHANGELOG.md
README.rst
doc/contrib/install.rst
doc/examples/docker.rst
doc/index.rst
oidc_example/op2/README.md
oidc_example/op2/server.py
oidc_example/op3/README.md
setup.py

Fix links after repo move

---

CHANGELOG.md
doc/conf.py
setup.py
src/oic/utils/settings.py

Improve settings by using pydantic

---

.readthedocs.yaml

---
Add proper requirements to RTD.

Fix building of the documentation

---

setup.py

Pin autodoc_pydantic to >=2.0.0 

---

setup.py
src/oic/oic/provider.py

Fix errors reported in quality

---

doc/examples/rp.rst

---
Two notes in the RP section were missing due to a syntax error in the note directives (missing space).

Docs: RP: Fix note directives so they are rendered in the HTML docs
