CZ-NIC/pyoidc

doc/howto/rp.rst
Do the authz request by redirecting the user instead of sending a direct request.
=> Updated cookbook to show simple authz request.

oidc_example/op2/server.py, src/oic/utils/shelve_wrapper.py
Added a shelve_wrapper which is needed by the OP to get access to an up to date client_db if the database is modified by an external process.
=> Support external static clinet registration server

src/oic/oic/provider.py
authz is passed client_id as kwarg
uic dict is trimmed according to permissions in session
- permissions is a list with allowed claims
=> Authz tunning

src/oic/utils/sdb.py, tests/test_oic_consumer.py
This is not used anywhere and may be hard or even impossible to
implement with some DBs
=> Remove keys() from SessionDB

src/oic/oic/provider.py
Meant mainly for altering endpoints if they are desired to have trailing slash but allows override of almost anything.
=> Setup available in create_providerinfo

src/oic/oic/message.py
dtto as in https://github.com/rohe/oictest/pull/86
• If the ID Token contains multiple audiences, the Client SHOULD verify that an azp Claim is present.
• If an azp (authorized party) Claim is present, the Client SHOULD verify that its client_id is the Claim Value.
=> Fix for typo in id_token validation.

src/oic/oic/provider.py
Allows to override used schema to create userinfo response.
This allows to add custom claims.
Used schema should inherit from OpenIDSchema.
=> Oic Provider takes schema kwarg

src/oic/utils/sdb.py
Use hashlib for public sub as well. Python hash() is not reliable in
generating the hashes. Updates & restarts might cause different hashes
for the same conditions.
Sorted imports according to PEP8.
=> Use hashlib for public sub generation

src/oic/oauth2/provider.py, src/oic/oic/provider.py, src/oic/utils/sdb.py, tests/fakeoicsrv.py, tests/mitmsrv.py, tests/oic/oic/test_oic_provider.py, tests/oic/utils/test_sdb.py
During client registration a random salt is generated and stored in
`cdb`. This is used in pairwise sub creation.
AuthnEvent now takes user-specific salt which can be returned from
authenticated_as() and is used in public and pairwise sub creation.
=> Updated sub creation

src/oic/oic/provider.py
There is an issue on the user endpoint when it tries parse userinfo_request, it replace '+' character to ' ' for access_token which causes a problem in retrieving type and key from access token.
```
uireq = self.server.parse_user_info_request(data=request)
|--- request().from_urlencoded(query)
|------- urlparse.parse_qs(urlencoded)
|-------------- unquote(nv[1].replace('+', ' '))
```
If you follow the ```parse_user_info_request``` method, you will find that for access_token ```urlparse``` library replace '+' with space. That creates a problem in the following line:
```
typ, key = _sdb.token.type_and_key(_token)
```
=> Fix access_token unquote issue

src/oic/oic/provider.py, src/oic/utils/sdb.py, tests/fakeoicsrv.py, tests/test_oic.py, tests/test_sdb.py
It is intended to be stored in non-volatile way to allow functionality
even if SessionDB had been restarted
Refresh token format changed to allow easier recognition
=> Separated Refresh token storage

src/oic/oic/provider.py, tests/test_oic_provider.py
_access_token can be malformed or the session might not exist at all.
This should result in error response and not in server error
=> Fix KeyError in _access_token_endpoint

src/oic/utils/sdb.py
Without this change, if you do:
```python
db = dict()
sdb1 = SessionDB('iss1', db=db)
sdb2 = SessionDB('iss2', db=db)
```
Then `sdb1._db == sdb2._db` would not be True, but it should be.
=> Better falsy check for passing db kwarg to oic.utils.sdb:SessionDB

src/oic/oauth2/message.py, src/oic/oic/message.py, tests/test_oauth2_message.py, tests/test_oic_message.py
OIC verification fails with KeyError if scopes are missing completely.
It should instead produce an error message.
=> Produce ErrorResponse if scopes missing completely

src/oic/extension/client.py
See http://astrofrog.github.io/blog/2016/01/12/stop-writing-python-4-incompatible-code/.
=> Make Python 2 special case, not Python 3.

src/oic/oic/provider.py, tests/test_oic_provider.py
I ran into this error message working through https://github.com/rohe/ojou_course and didn't understand what it meant at first until I reviewed source. As soon as I realized it meant "non-https URL not allowed" it was easy to fix my problem.
=> Fix typo in error message.

doc/howto/rp.rst
Everywhere else this variable is referenced, it's called `client`, so I thought it a good idea to keep it consistent.
One more note: changes to this document are not propagating to [readthedocs](http://pyoidc.readthedocs.org/) so [this page](http://pyoidc.readthedocs.org/en/latest/howto/rp.html) still has a very old version of this documentation.
=> Changed c to client for consistency

src/oic/oic/provider.py
I was having trouble registering clients with redirect_uris that have query strings
e.g. http://localhost:3000/authenticate?action=openid-connection-authorize
The response would come back like 
```
"redirect_uris": [
"http://localhost:8888/livefyre-portal/html/how-to-landing-page/?{u'action': [u'openid-connect-authorize']}"
],
```
This should fix it.
=> FIx comb_uri

src/oic/utils/authn/user_cas.py
Fix CAS login URI per protocol spec.
=> Issue #190 CAS login URI is /login.

src/oic/oauth2/message.py, src/oic/oic/message.py, tests/test_oic_message.py
To make sure all required attributes are present, before any special handling is performed.
=> Always call verify() in superclass first.

src/oic/oauth2/message.py
Will only be included in the request body for client authentication.
=> Client identifier is not required in RefreshAccessTokenRequest.

src/oic/utils/authn/client.py, tests/test_client.py
b64e_enc_dec removes any trailing '=', which should be left
for HTTP Basic auth.
=> Don't truncate padding for HTTP Basic auth.

src/oic/utils/sdb.py
Because that way uid2sid is reasonably notified of the update (in case it is not a dictionary)
=> Don't append to value of uid2sid, instead `+=`

src/oic/utils/http_util.py, tests/test_http_util.py
Fixes https://github.com/rohe/pyoidc/issues/202
This change avoids triggering an exception in `SimpleCookie()` when it's passed a string type in Python 2.7.
=> Fixes unicode/binary problems with SimpleCookie on Python 2.7

src/oic/utils/sdb.py
Use the `token_factory` directly.
=> Fix refreshing of access_token if `sid` missing

src/oic/oic/consumer.py
`ErrorResponse` subtypes no longer have `type()`, determination of ErrorResponse should be by instance.
=> ErrorParsing at consumer

src/oic/utils/authn/client.py, tests/test_client.py
According to specification, client_secret_expires_at == 0 should be
treated as never expires.
=> Tweaked valid_client_info

src/oic/oic/provider.py
The direct assignment might not work for anything else than dict()
=> Use sdb.update() to change keys in session

src/oic/oic/message.py, tests/test_oic_message.py
Only 'request_object' ends with '_encryption_*', 'id_token' and
'userinfo' ends with '_encrypted_response_*'.
=> Verify the correct encryption params in RegistrationRequest.

oidc_fed/oidcfed.txt, oidc_fed/oidcfed.xml
This version updates the date to September 9th (the date of the last commits) and uses version number -01, since the last version published at openid.net/specs/ was -00.  This version has been published as http://openid.net/specs/openid-connect-federation-1_0-01.html.
=> openid-connect-federation-1_0-01

src/oic/oauth2/message.py
Allows for using IdToken.jwt for `id_token_hint` in e.g. end session requests.
=> Preserve the parsed JWT when unpacking Messages.

oidc_example/op1/oc_server.py, oidc_example/op2/server.py, oidc_example/rp2/rp2.py, oidc_example/rp3/rp3.py
This addresses https://github.com/rohe/pyoidc/issues/232
=> examples: make static file handlers return bytes instead of text

src/oic/extension/client.py, src/oic/extension/provider.py, src/oic/oauth2/__init__.py, src/oic/oauth2/base.py, src/oic/oauth2/consumer.py, src/oic/oauth2/message.py, src/oic/oauth2/provider.py, src/oic/oauth2/util.py, src/oic/oic/__init__.py, src/oic/oic/claims_provider.py, src/oic/oic/consumer.py, src/oic/oic/provider.py, src/oic/utils/authn/authn_context.py, src/oic/utils/authn/client.py, src/oic/utils/authn/user.py, src/oic/utils/authz.py, src/oic/utils/keyio.py, src/oic/utils/rp/__init__.py, src/oic/utils/rp/oauth2.py, src/oic/utils/sanitize.py, src/oic/utils/userinfo/distaggr.py, src/oic/utils/userinfo/ldap_info.py, tests/test_oauth2_provider.py, tests/test_requirements.txt, tests/test_sanitize.py, tests/test_user.py, tox.ini
Fixes #228
- Adds `oic.utils.sanitize.sanitize()` function that makes a best-effort attempt to remove sensitive data from mappings and strings. 
- Applies `sanitize()` throughout the codebase on log entries.
- Removes or modifies some log entries I wasn't confident could be sanitized, or that seemed like they would be uninformative after sanitizing. 
- Makes `oic.oauth2.message.Message` into a subclass of `MutableMapping` to make life easier for the `sanitize()` function.
- Adds a nicer `__repr__()` for the `KeyJar` to make testing easier.
- Slightly changes sorting behavior on `authn_context` to get consistent test output.
- Adds tests for `sanitize()`
- Extends some existing tests to verify their logs are clean.
- Modifies tox.ini to allow passing extra arguments in to the test runner.
=> Sanitizes log entries to remove sensitive data

src/oic/oauth2/base.py
The current code in PBase does not respect `verify_ssl` set to True:
```
if ca_certs:
self.request_args["verify"] = verify_ssl
```
That is, it only sets `request_args["verify"]` to `True` if `ca_certs` evaluates to True (`verify_ssl` is effectively ignored).
That code also does not respect `ca_certs`, if given (because if it is given, the underlying requests argument is not populated with `ca_certs`).
This PR improves the handling of the pyoidc-specific HTTP client args `verify_ssl` and `ca_certs`, and translates them into the expected `verify` argument value of the requests package.
=> oauth2/base: consolidate usage of requests arguments for server cert verification.

.travis.yml
We should test against the latest point releases. Especially in case of Python 3.5 (the changes between 3.5.0 and 3.5.2 are significant).
=> Travis CI: test against CPython 3.4.4 and 3.5.2

requirements.txt
Upgrades `cryptography` and `cffi` to >1.0 versions. Needed to fix https://github.com/pyca/cryptography/issues/2750 on Ubuntu 16.04.
=> Upgrade cryptography and cffi

src/oic/oauth2/provider.py, tests/test_oauth2_provider.py
`get_redirect_uri` can throw `UnknownClient` when `client_id` is missing either in request or in client database.
=> Catching UnknownClient in auth_init

src/oic/oic/provider.py, tests/test_oic_provider.py
This allows for an easier override of the returned value.
=> Client_secret_expires_at separated in method

src/oic/oic/__init__.py, tests/test_oic_provider.py
This was hiding errors in message and allowed them to resurface when not expected.
Example of this is offline_acces without prompt.
=> Reraise logged Exception in parse_authorization_request

doc/install.rst, requirements.txt, tests/test_requirements.txt
`python-ldap` kinda holds the Python 2/3 compatibility back.
`pyldap` is *supposed to be* a drop-in replacement fork. 
Let's see what Travis CI says.
=> Add Python3 compatible LDAP replacement.

doc/install.rst
I ran into a really nasty `pycryptodome` bug that was the result of ignoring bye-compiling. 
Here's a note so nobody else will fall into that (hopefully!).
=> Update documentation: compat and byte compiling note.

src/oic/oic/__init__.py
Some software (like google) has strict requirements for it, and specification says `should` about `Bearer`. So converting any lowercase header here to capitalized. Headers like JWT or Someheader shall be untouched.
=> Convert 'bearer' to 'Bearer' for HTTP headers

.travis.yml, CHANGELOG.md
2.7, 3.5 and 3.6 are tested now.
=> Drop 3.4.4 and cover more relevant versions.

.gitignore, CHANGELOG.md, Makefile, doc/conf.py, doc/index.rst, requirements/admin.in, requirements/base.in, requirements/base.txt, requirements/docs.in, requirements/docs.txt, requirements/test.in, requirements/test.txt
---
So, the two main things I have done here are:
1) Remove code index generation
2) Add a separate documentation dependency
Why? For 1), I think the index generation depends on the library being installed, which we cannot have installed on the readthedocs platform because the `pyldap` dependency requires some system dependencies, and readthedocs cannot install anything on the system (phew!).
For 2), well, I don't know why this was missing but it should be a seperate dependency.
=> Fixup documentation building

src/oic/oic/provider.py, tests/test_oic_provider.py
- [#295 ] Fixed a bug in the _refresh_access_token_endpoint method that prevented new Access Token from being issued . The second fix was for a spelling error in the verify_redirect_uris method.
The effect of the spelling error was that an exception was thrown if a redirect_uri that a native app tried to register didn't adhere to what the standard says. Added tests for both these fixes.
---
=> Wrong token was used to find the session id.

CHANGELOG.md, requirements/admin.txt, requirements/base.in, requirements/base.txt, requirements/docs.txt, requirements/test.txt
As mentioned in #188 `future` is used in the code explicitly, thus it should be present in requirements.
Close #188
---
=> Add future to dependencies, upgrade dependencies

CHANGELOG.md, pylama.ini, src/oic/utils/authn/saml.py
=> Decrease complexity of authn/saml.py

CHANGELOG.md, src/oic/utils/client_management.py
In PR #117 commit 4e1ae5ab8a889b57a59f9c5d9ecf6df04fdaaf4f breaks the client_management module under Python 2 because of the change of the input builtin in Python 3.
This imports the Python 3 function from `future`
Fixes #330 
---
=> Fix python 3 input syntax for python 2 support

.coveragerc, .travis.yml, README.rst, requirements/test.in, requirements/test.txt, tox.ini
Adding test coverage to CI.
We will need to enable Coveralls.
---
=> Add test coverage to CI

src/oic/oic/provider.py, tests/test_oic_provider.py
Refactoring of `oic.oic.provider.Provider.do_clinet_registration` in order to decrease McCabe score.
---
=> Moved sector_identifier checks outside

src/oic/oic/provider.py
=> Use urljoin instead of os.path.join when joining URLs

CHANGELOG.md, src/oic/utils/sdb.py
This fixes the constant IV issue in #349 by using the fernet scheme to do the encryption.
This does not yet add a KDF function to stretch a weak password into some stronger key. This is okay if the 'password' is not really a password but a high entropy key. 
It is still 'padding compatible' with the old Crypt code, even if the benefits of manual padding to the AES blocksize seems doubtful.
=> Better token crypto

src/oic/oic/__init__.py
According to RFC6749 an OP shall return a 400 when it encounters an error in processing a request.
The OIDC core document in section 5.3.3 in the example uses 401.
During conformance testing I've also seen 403's in some cases.
So, there is reason to widen then scope for possible status_code denoting protocol errors.
The fact that I've seen software return a 200 with an error message is another matter and is already covered in the code.
=> Status code can be 400, 401, 403 or .. !

src/oic/oauth2/consumer.py, src/oic/oic/consumer.py, tests/test_oic_consumer.py, tests/test_time_util.py
Fixes some broken tests on Windows:
- stateID() was not unique when called twice, due to the low clock resolution on windows, so the clock timestamp didn't change between the
two test calls
- stateID code was duplicated between oauth2/consumer.py and oic/consumer.py
- test_begin_file makes invalid assumptions about the externally visible URL path and the local filesystem path
- test_a_while_ago falls into the same trap as stateID() and does not account for the fact that time is quantized/discreet instead of continous
=> Win test failures

CHANGELOG.md, src/oic/oic/__init__.py, tests/test_claims.py, tests/test_oic.py, tests/test_oic_provider.py
Modified claims_match to correctly implement what's specified in section 5.5.1 of http://openid.net/specs/openid-connect-core-1_0.html.
Also added tests to increase coverage and make it clearer what the function is expected to do.
=> Fixed claims_match and added tests.

CHANGELOG.md, src/oic/exception.py, src/oic/extension/provider.py, src/oic/oauth2/provider.py, src/oic/oic/claims_provider.py, src/oic/utils/authn/user.py, src/oic/utils/http_util.py, tests/conftest.py, tests/test_authn_user.py, tests/test_http_util.py, tests/test_oic.py, tests/test_oic_consumer.py, tests/test_oic_provider.py
---
Follows from https://github.com/OpenIDC/pyoidc/issues/322.
=> Make symkey an optional kwarg.

CHANGELOG.md, README.rst, src/oic/oic/provider.py, src/oic/utils/sdb.py, tests/test_oic_provider.py, tests/test_sdb.py, tests/test_token.py
---
This takes a naive approach to solving this issue:
1. I use the `__dict__` attribute to take the useful data from the AuthnEvent object
2. Use the dict access syntax for the `session['authn_event']` from there onwards
3. Rebuild the object with `AuthnEvent(**session['authn_event'])` to use the `valid()` function
3a. I add new kwargs to the AuthnEvent `__init__`
Another approach would be to use [the jsonpickle](https://jsonpickle.github.io/) package, but I was thinking this was a nice simple approach without the new dependency.
This will close off https://github.com/OpenIDC/pyoidc/issues/360.
=> Serialize the AuthnEvent when adding to session

src/oic/oic/provider.py
I have use cases where that is not true.
=> base URL according to urljoin can only contain one path component.

CHANGELOG.md, src/oic/utils/aes.py, src/oic/utils/http_util.py, tests/test_aes.py, tests/test_http_util.py
Added per cookie IV's to the CookieDealers encryption handling.
This fixes #363.
Also restyled the encrypt and MAC construction for cookie security to
use a more modern AEAD approach.
In this case it is AES-SIV (RFC  5297), which has the nice property to
be a bit resistant to IV reuse.
=> Improve cookie crypto for CookieDealer

CHANGELOG.md, requirements/base.txt, setup.py, src/oic/oauth2/message.py, tests/test_oauth2_message.py
- [x ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
to_jwe/from_jwe using elleptic curve crypto is dependent on pyjwkest to be of version 1.3.3 or later to work.
=> to_jwe/from_jwe fix

src/oic/oic/message.py
Should not accept an ID Token from anyone but the expected one.
=> Make sure the issuer of the ID Token is the correct one.

CHANGELOG.md, Pipfile, Pipfile.lock, src/oic/oauth2/message.py, src/oic/oic/__init__.py, src/oic/oic/message.py, src/oic/oic/provider.py, src/oic/utils/keyio.py, tests/test_keyio.py, tests/test_oauth2_message.py, tests/test_oic_message.py, tests/test_oic_provider.py
---
Working with the OP test tools a misbehaviour in pyoidc became obvious.
In protocol messages the value None on a parameter means that that parameter should just be ignored.
This is not true for Claims and IDToken's. 
None values on parameters in either of these messages should be regarded as errors.
There also where some transformation errors when creating Message instances.
Most notably a non-integer was accepted as a value to a parameter marked as having integer value.
And lastly a problem with Python was discovered.
For some reason isinstance(True, int) == …
=> Decode and verify

CHANGELOG.md, oauth_example/as/as.py, oidc_example/op1/claims_provider.py, oidc_example/op1/oc_config.py.example, oidc_example/op1/oc_server.py, oidc_example/op2/server.py, oidc_example/op3/server.py, oidc_example/simple_op/src/provider/server/server.py, src/oic/utils/sdb.py, tests/conftest.py, tests/fakeoicsrv.py, tests/mitmsrv.py, tests/test_claims_provider.py, tests/test_oauth2_provider.py, tests/test_oic.py, tests/test_oic_consumer.py, tests/test_oic_provider.py, tests/test_sdb.py, tests/test_token.py, tests/test_x_client.py, tests/test_x_dynreg.py, tests/test_x_provider.py
Refactor the SessionDB constructor to be less overloaded.
Looking into #326 i found the password and secret parameters are only used when a DefaultToken factory is used, so they do not really belong into the SessionDB class, if we externalize the factories. The seed parameter is not used at all.
So i threw out the parameters from the __init__ and wrote a wrapper that is nearly as convenient as the old API for the test/example cases.
This partially fixes https://github.com/OpenIDC/pyoidc/issues/326 as the defaults are gone, but DefaultToken does not raise nice exceptions yet.
This is still work-in-progress, just wanted to get some extra looks and agreement about the direction this goes.
It would still be nice to refactor a bit more (e.g. the RefreshDB/RefreshTokenFactory divide seems …
=> Refactor SessionDB constructor and use secure defaults

CHANGELOG.md, src/oic/oauth2/provider.py, tests/test_oauth2_provider.py
=> Correctly create error response when wrong response_mode requested

src/oic/oic/__init__.py, tests/test_oic.py
Fixed bug in handling of distributed claims.
---
=> Distributed claims

CHANGELOG.md, src/oic/utils/authn/client.py, tests/test_client.py
=> Audience is endpoint dependent.

CHANGELOG.md, src/oic/oic/__init__.py
Headers was passed as list instead of as a dictionary.
- [x ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
---
=> Fix headers for read_registration

CHANGELOG.md, src/oic/oic/provider.py, tests/test_oic_provider.py
=> Add support for extra_claims

CHANGELOG.md, src/oic/oic/provider.py, tests/test_oic_provider.py
=> Fix KeyError on provider.read_registration

.travis.yml, README.rst, tox.ini
=> Use Codecov instead of coveralls

.travis.yml, tox.ini
Reorganized `.travis.yaml` to use matrix. This makes it possible to run tests under python 3.5.
=> Add travis builds under python 3.5

CHANGELOG.md, src/oic/oic/provider.py, tests/test_oic_provider.py
=> Support for configuration endpoint

CHANGELOG.md, src/oic/extension/provider.py, src/oic/oauth2/provider.py, src/oic/oic/provider.py, src/oic/utils/http_util.py, tests/test_oauth2_provider.py, tests/test_oic_provider.py, tests/test_x_provider.py
=> Add no-cache headers to token endpoints

src/oic/oic/provider.py
I think this is an error. Issuer value should be taken from self.name and not self.baseurl (which might be different).
---
=> Wrong issuer value in response when iss != baseurl

CHANGELOG.md, src/oic/oauth2/util.py, tests/test_util.py
=> Allow endpoints to have query parts.

src/oic/oic/__init__.py, tests/test_oic.py
see: openid-certification/oidctest#70
this avoids falling into the Exception handler that tries to decode an error registration response error which would trigger another exception that isn't handled
Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
---
=> make message about missing registration attribute available to tester

CHANGELOG.md, doc/examples/tls.rst, doc/index.rst, oidc_example/op1/oc_server.py, oidc_example/op3/server.py, oidc_example/rp2/oidc.py, src/oic/extension/client.py, src/oic/oauth2/__init__.py, src/oic/oauth2/base.py, src/oic/oauth2/provider.py, src/oic/oic/__init__.py, src/oic/oic/claims_provider.py, src/oic/oic/provider.py, src/oic/utils/keyio.py, src/oic/utils/rp/__init__.py, src/oic/utils/rp/oauth2.py, tests/test_oauth2_consumer.py
Remove the ca_certs option that was not handled consistently.
Now our verify_ssl option has the same semantics as the requests verify option.
Also added a few words about TLS in the documentation.
This fixes https://github.com/OpenIDC/pyoidc/issues/471
=> Remove ca_certs option and replace it by verify_ssl

CHANGELOG.md, tests/test_oic_provider.py
Fix the test_provider_key_setup test.
The code under test makes bad assumptions about the filesystem layout.
Basically key_setup/key_export only work for a very specific setup where the export dir is inside the web servers root directory.
The test ignored this assumption and just tried to stuff any random tmpdir path there, which does not work.
The fix just adjusts the tempdir path to a local name, that works.
This should kind of fix https://github.com/OpenIDC/pyoidc/issues/352.
=> Fix broken test on windows

src/oic/utils/authn/client.py, tests/test_oic.py
this reverses https://github.com/OpenIDC/pyoidc/commit/c0e267040c351cf670ff03c1d70361d4ae024ead done because of https://github.com/OpenIDC/pyoidc/pull/235 which incorrectly refers to OAuth RFC section 3.2.1 (which is about unauthenticated clients that MUST send it); also MS confirms that Azure AD does not need it (anymore)
see:
https://github.com/openid-certification/oidctest/issues/61
and:
https://mailarchive.ietf.org/arch/msg/oauth/OPFwxoO0U1ogYtOA54XwEaali6w
although technically allowed, it reduces interoperability and pyoidc should be strict in what it sends
Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
---
=> do not include client_id in access token requests that use basic auth

CHANGELOG.md, src/oic/oic/provider.py, src/oic/utils/sdb.py, tests/test_oic_provider.py, tests/test_sdb.py
=> Validate expiration of Token at UserInfo endpoint

src/oic/extension/token.py, src/oic/oic/provider.py, src/oic/utils/sdb.py, tests/test_sdb.py
Encoded the issued at timestamp in the DefaultToken, so we can check it later.
The specific factories are responsible for checking the tokens they issued.
This fixes the broken tests introduced with PR #482.
Old DefaultToken issued tokens will need to be reissued, JWTTokens stay valid with this change. But due to the problems with randomness it is a good idea to re-issue all tokens anyway.
=> Better fix for token expiry check

.gitignore, CHANGELOG.md, src/oic/__init__.py
This fixes https://github.com/OpenIDC/pyoidc/issues/486 .
This is a pretty bad security issue, as the secrets used to initialize most crypto is created by `rndstr`, so one can probably brute force things with some small effort (e.g. using untwister and some known values).
=> Fix broken import of SystemRandom

CHANGELOG.md, oidc_example/op1/claims_provider.py, oidc_example/op1/oc_server.py, oidc_example/op2/server.py, oidc_example/op3/server.py, oidc_example/simple_op/src/provider/server/server.py
The examples overwrote the endpoints method, instead of setting the endp member variable.
This fixes the Issue #370.
=> Fix endpoints usage in examples

CHANGELOG.md, src/oic/oauth2/__init__.py, src/oic/oic/provider.py, src/oic/utils/http_util.py
=> Remove methods and functions deprecated in previous releases

CHANGELOG.md, src/oic/utils/jwt.py, tests/test_jwt.py
=> Fix verification of JWT using verify keys

CHANGELOG.md, src/oic/extension/provider.py, tests/test_x_provider.py
IntrospectionEndpoint should return regular response with active=False
if it cannot verify the activity of the token for any reason.
Close #502
---
=> Fix responses from IntrospectionEndpoint

CHANGELOG.md, src/oic/oic/__init__.py
Close #492
Disabled the verification of distributed claims for now. It is not very clear from specifications what should we do in order to retrieve the correct keys.
---
=> Disable verification of JWT from distributed claims

README.rst
Fixed by deleting additional point at the end of the url.
=> Fix spec url

CHANGELOG.md, src/oic/oic/provider.py, tests/test_oic_provider.py
---
This can happen in some cases for offline access if users implement their own Refresh storage. The AuhtnEvent is pointles in this case anyway as it might be already invalid.
=> Fix userinfo with missing authn_event in session

CHANGELOG.md, src/oic/oauth2/__init__.py, src/oic/oauth2/grant.py, tests/test_grant.py, tests/test_oic.py
=> Remove replaced tokens on `do_access_token_refresh`

src/oic/utils/http_util.py
---
Ran into this small bug running in Python 3 for redirect responses.
=> Avoid TypeError in Python 3.x from integer status codes

src/oic/oic/__init__.py
Instead raising the provider configuration this PR will catch ValueError from the ProviderConfigurationResponse.from_dict() and present that as the error message.
Instead of this
```
ParseError: Faulty provider config response: {
"token_endpoint_auth_signing_alg_values_supported" : [ "RS256" ],
"id_token_signing_alg_values_supported" : [ "RS256" ],
"userinfo_endpoint" : "https://example.org/userinfo",
"authorization_endpoint" : "https://example.org/authorize",
"token_endpoint" : "https://example.org/token",
"jwks_uri" : "https://example.org/jwks",
"claims_supported" : [ "family_name", "given_name", "name", "auth_time", "iss", "sub" ],
"scopes_supported" : [ "openid" ],
"subject_types_supported" : [ "public" ],
"response_types_supported" : [ "code" ],
"claims_parameter_supported" : …
```
=> Catch ValueError for better error message

src/oic/oic/message.py
see openid-certification/oidctest#93
see http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata where the default is "False" if not provided
Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
---
=> change require_request_uri_registration default value to False

CHANGELOG.md, src/oic/oic/provider.py, tests/test_oic_provider.py
=> Fixed uncaught exception from oic.provider.Provider.auth_init

CHANGELOG.md, src/oic/oauth2/__init__.py, src/oic/oauth2/base.py, src/oic/utils/keyio.py
=> Requests timeout

CHANGELOG.md, src/oic/oic/__init__.py, tests/test_oic_consumer.py
=> Fix get_userinfo_claims on consumer

CHANGELOG.md, src/oic/utils/sdb.py, tests/test_sdb.py
=> Fix SessionDB.revoke_token implementation

CHANGELOG.md, src/oic/utils/keyio.py, tests/test_keyio.py
=> Bunjiboys jwks content type

CHANGELOG.md, src/oic/oauth2/provider.py, src/oic/oic/provider.py, src/oic/utils/authn/user.py, src/oic/utils/authz.py, tests/mitmsrv.py, tests/test_oic_provider.py
=> Client id in cookie

CHANGELOG.md, src/oic/oauth2/provider.py, tests/test_oauth2_provider.py
=> Do not append cookie_header if there is nothing to append

CHANGELOG.md, src/oic/utils/http_util.py, tests/test_http_util.py
=> Add secure and httponly to CookieDealer

src/oic/oauth2/__init__.py, tests/test_oauth2_consumer.py, tests/test_oic.py
---
It fixes the issue we discovered on #608
=> Fix: Grant storage for access tokens response subclasses

CHANGELOG.md, setup.py, src/oic/utils/client_management.py, src/oic/utils/clientdb.py, tests/utils/test_client_management_run.py
---
Hi PyOIDC maintainers! It seems to me that this `src/oic/utils/client_management.py` script is key to getting examples running for us new-comers. :) Here's a PR that lifts it up in 3 ways:
1. Extends the command-line interface with some user-friendly long-form option names
2. Fixes a bug where `-l` (or `--list`) would output some "KeysView" memory reference instead of client IDs
3. Adds it to `setup.py` to be installed as a Python environment-local `oic-client-management` CLI tool (invoking it with `python full-filepath/to/script.py ...` still works as before of course)
=> `client_management.py` CLI

CHANGELOG.md, src/oic/extension/provider.py, src/oic/oauth2/provider.py, src/oic/oic/provider.py, tests/test_oauth2_provider.py, tests/test_oic_provider.py
All three providers (oauth2, oic and extension) now share common code.
---
Prep work for #615 and #617.
Also getting rid of duplicated code...
=> Synced implementation of token_endpoint

CHANGELOG.md, src/oic/oauth2/__init__.py, src/oic/oic/__init__.py
---
A touch of refactoring. Pruned Server classes.
=> Refactor Server classes.

src/oic/oauth2/provider.py, src/oic/oic/provider.py
---
Touch of refactoring, Updated Provider classes.
=> Refactor Provider classes

CHANGELOG.md, src/oic/oic/claims_provider.py, src/oic/utils/authn/client.py, tests/test_claims_provider.py
It was used on only one place and contains `assert`.
---
=> Deprecate `bearer_auth` helper method

oidc_example/simple_op/requirements.txt
Older versions have a security issue and github complains about it.
See CVE-2019-8341.
It does not really affect pyoidc, as the bug is only in SandboxedEnvironment which isn't used.
=> Update Jinja2 dependency for simple_op2

Makefile, oidc_example/op3/server.py, setup.py
Adding the bandit tool to the toolbox.
https://github.com/PyCQA/bandit
And fix some trivial py3 syntax errors in the op3 example so it doesn't blow up right away when running the bandit.
As we have some security sensitive code here, we probably should run some basic scanner like that to catch the simpler issues. Its not good enough for the CI yet, but give it a try.
Running it only on code & examples, as the tests do not need and cannot be secure.
=> Add bandit to the quality tools

doc/examples/cookbook.rst
=> Add client assertions to cookbook.rst

CHANGELOG.md, src/oic/oic/provider.py, src/oic/utils/sdb.py, tests/test_oauth2_provider.py, tests/test_oic_provider.py, tests/test_sdb.py, tests/test_token.py
=> Shared sessiondb

CHANGELOG.md, src/oic/extension/client.py, src/oic/oauth2/__init__.py, src/oic/oauth2/provider.py, src/oic/oic/__init__.py, src/oic/oic/provider.py, tests/test_oic.py
---
The failing integration tests have a PR already, so we just need to wait till it gets to upstream and re-run.
=> Removed deprecated request/response_cls kwargs

CHANGELOG.md, src/oic/oauth2/message.py, src/oic/oic/provider.py, tests/fakeoicsrv.py, tests/test_oauth2.py, tests/test_oauth2_message.py, tests/test_oic_message.py
Raise DecodeError on all failures.
Close #602
---
=> Properly handle incorrect message decoding.

CHANGELOG.md, src/oic/oic/__init__.py, tests/test_oic.py
'state' in kwargs is used as a key to access information in the RP.
'state' in request_args is just a request argument.
They are not necessarily the same.
---
=> 'state' in kwargs MUST NOT overwrite 'state' in request_args.

CHANGELOG.md, src/oic/oauth2/grant.py, src/oic/oauth2/message.py, src/oic/oic/__init__.py, src/oic/oic/message.py, tests/test_grant.py, tests/test_oic.py
=> Wants the original non-parsed JWT and not an IDToken instance.

CHANGELOG.md, src/oic/oic/provider.py, tests/test_oic_provider_logout.py
---
If no post_logout_redirect_uris are registered and no post_logut_redirect_uri appears in the
request, the user will be redirect to a post logout uri defined by the OP.
=> Allow no post_logout_redirect_uri

CHANGELOG.md, src/oic/oic/provider.py
---
According to spec the POST body uses the application/x-www-form-urlencoded encoding.
=> Set Content-Type for backchannel logout POSTs

CHANGELOG.md, src/oic/oic/message.py, tests/test_oic_message.py
---
The Front-Channel and Back-Channel specs say that frontchannel_logout_session_supported and backchannel_logout_session_supported SHOULD be registered but that if they're not present, their default values are false.
=> Missing OP metadata parameters.

CHANGELOG.md, src/oic/oic/__init__.py, tests/test_oic_consumer.py
When register an OpenID Client,
registration tokens that are valid JWTs are now passed through to the
OpenID Provider. Every other string is still base64 encoded.
This closes #718 
Don't know if the previous two are applicable.
---
=> Allow OpenID Client registration with JWT

CHANGELOG.md, src/oic/oic/__init__.py, tests/test_oic.py
Hi,
I wrote a client with that supports multiple providers. One of the providers restricts the HTTP Method
to GET. I don't want to restrict every provider to only use get, maybe the next will only support POST.
Since clients must return allowed methods, I looked into the http header and retry the userinfo request. If this is wanted behaviour, I would write test code for this.
Else, I would at least raise a different exception, since the resp.text is in my case empty and the
status code is not returned.
---
=> Handle HTTP 405 (method not allowed error)

src/oic/utils/sanitize.py
Currently when using this library I get the warning
```
path\to\site-packages\oic\utils\sanitize.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Mapping
```
Since the min python version is 3.5 this can be safely changed
=> Remove deprecation warning: import Mapping from collections.abc

tox.ini
---
`isort` in quality build uses deprecated option. Remove it from usage.
I wasn't able to remove the warning about distutils, it will go away in newer versions of python (doesn't show up in 3.8 for me) but I am not sure if we want to switch the quality to newer python or not.
=> Clear quality output

appveyor.yml
=> Unbreak appveyor.yml after cryptography update

src/oic/extension/provider.py, src/oic/oauth2/provider.py, src/oic/oic/provider.py, src/oic/utils/client_management.py, tests/test_oauth2.py, tests/test_oic.py, tests/test_oic_consumer.py
Fix the deprecated splitquery calls.
---
=> Remove deprecated urllib.parse.splitquery calls

doc/examples/docker.rst
Replace the broken double-pasted URL with a working one pointing to the
downloads page for Docker CE.
=> doc: fix Docker URL

README.rst
The `pyoidc-dev` mailinglist doesn't exist anymore and it seems there's
no replacement for it - so remove the reference to it altogether.
=> README: remove mailinglist reference

src/oic/utils/keyio.py
- No changes relevant to users
- No documentation update needed
- Not relevant
- Not relevant
---
Hey,
I replace a debug log line using directly `logging` by the use of the `logger` instance.
Otherwise, while configuring `oic` logging to level `INFO` in my application, I still get a `DEBUG` root login `KeyBundle fetch keys from: <url>`
I can't figure out any reason to use `logging` here.
=> fix: use logger instance rather than raw logging

setup.py
Just adding 3.9 to the supported list.
---
=> Add mention of Python 3.9 in the trove classifier list

CHANGELOG.md, pylama.ini, src/oic/oauth2/__init__.py, tests/test_oauth2.py
=> Support for dict in Client.parse_response formats

README.rst
travis-ci.org is officially dead since 15 of June 2021, so this is now useless.
---
=> Remove Travis Build Banner

oidc_example/op2/static/bootstrap/css/angular.js, oidc_example/op3/static/bootstrap/css/angular.js, src/oic/utils/keyio.py, src/oic/utils/sdb.py, src/oic/utils/time_util.py
There are small typos in:
- oidc_example/op2/static/bootstrap/css/angular.js
- oidc_example/op3/static/bootstrap/css/angular.js
- src/oic/utils/keyio.py
- src/oic/utils/sdb.py
- src/oic/utils/time_util.py
Fixes:
- Should read `unnecessary` rather than `unecessary`.
- Should read `preferable` rather than `preferrable`.
- Should read `obsolete` rather than `obsolte`.
- Should read `constitute` rather than `consititute`.
- Should read `persistent` rather than `persistant`.
- Should read `overridden` rather than `overriden`.
- Should read `according` rather than `accordign`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.github/workflows/python-test.yml, CHANGELOG.md, appveyor.yml, setup.py, tests/utils/test_client_management_run.py, tox.ini
=> Drop python 3.6

src/oic/extension/client.py, src/oic/oauth2/__init__.py, src/oic/oauth2/base.py, src/oic/oauth2/util.py, src/oic/oic/provider.py, tests/test_oauth2.py, tests/test_util.py, tests/test_x_client.py
---
This tries to cleanup the mess around the error handling in: https://github.com/OpenIDC/pyoidc/issues/807
The parse_request_response() method of the client has some horribly mixed return type for some very limited special cases. This change tries to untangle that mess a bit, by reducing the return types to just Message or requests.Response.
The special handling of an empty response is instead pushed to the Token Revocation code in the extension client that needs it.
=> Try to fix the generic response parsing and handling

CHANGELOG.md, mypy.ini, src/oic/oic/__init__.py, tests/test_oic.py
Addresses #826 
According to [OIDC specs on RP-Initiated logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html), the expected arguments are  `post_logout_redirect_uri` and `id_token_hint` that accepts raw ID token JWT.
Added a default parameter `id_token_hint` in `oic.Client.construct_EndSessionRequest` & `oic.Client.do_end_session_request` to make them comply with OIDC specs.
=> Fixed RP-Initiated Logout To Accept id_token_hint

CHANGELOG.md, src/oic/oic/message.py, tests/test_oic_message.py
Signed-off-by: Li Chaoran <pkwarcraft@gmail.com>
---
the code is straightforward, no need any comments :)
fix #830
=> fix for some provider return birthdate:null in userInfo

CHANGELOG.md, mypy.ini, src/oic/oauth2/__init__.py, src/oic/oauth2/base.py, src/oic/oauth2/provider.py, src/oic/oic/__init__.py, src/oic/oic/provider.py
=> Fix mypy errors with no_implicit_optional=True

tox.ini
=> Fix tox config for v4

src/oic/oauth2/__init__.py, tests/test_oauth2.py
---
When upgrading the `pyoidc` dependency from `1.4.0` to `1.5.0` in [Flask-pyoidc](https://github.com/zamzterz/Flask-pyoidc) it revealed a breaking API change (by breaking [this test](https://github.com/zamzterz/Flask-pyoidc/blob/6c55fbe304a39902a9c6374fd560845218461382/tests/test_pyoidc_facade.py#L205)): A`HttpError` exception is thrown for token error responses, without any possibility of recovering the error response.
This change brings back the [behavior in `1.4.0`](https://github.com/OpenIDC/pyoidc/blob/1.4.0/src/oic/oauth2/__init__.py#L738-L741) which returns the token error response allowing for further handling.
=> Don't throw exception for token error response.

oidc_example/rp2/oidc.py, src/oic/utils/authn/user_cas.py, src/oic/utils/clientdb.py, src/oic/utils/keyio.py
=> Pass timeout to all requests

doc/index.rst
=> Correct OpenID Connect Core specification URL in doc

CHANGELOG.md, src/oic/oic/consumer.py
- Documentation wasn't updated, because there is no relevant documentation about `Consumer.complete` at the moment.
- I didn't add any test because it's just an argument that's passed to the underlying function and it should  already be tested there.
---
Closes #851
=> Add authn_method to Consumer.complete()

CHANGELOG.md, src/oic/oic/consumer.py, tests/test_oic_consumer.py
This PR improves the support for [Open ID Connect session management](https://openid.net/specs/openid-connect-session-1_0.html).
When processing the *Authorization Response* from an *Authorization Server*, it allows library users to save the consumer data using the `session_state` parameter from the response.
This makes it easier to integrate this library in a webserver, as session keys are very usefull to find back the appropriate `Consumer` instance from the `SessionBackend`.
More details on the motivation behind this PR can be found in the following discussion : #853 
-----
=> Use session_state to backup consumer state if available

setup.py, src/oic/utils/settings.py
`BaseSettings` have been moved to `pydantic-settings` package under the same maintainer. As Pyoidc is using `BaseSettings` only in `oic.utils.settings`, we can change the dependency without any problem.
=> Moved dependency from pydantic to pydantic-settings

CHANGELOG.md, src/oic/extension/provider.py, src/oic/oauth2/base.py, src/oic/oauth2/consumer.py, src/oic/oauth2/provider.py, src/oic/oic/__init__.py, src/oic/oic/provider.py, src/oic/utils/authn/saml.py, src/oic/utils/http_util.py, src/oic/utils/keyio.py, src/oic/utils/rp/__init__.py, src/oic/utils/rp/oauth2.py, tests/test_oic_provider.py
---
When trying to hook opentelemetry up to the code, it blows up trying to consume log messages without a format string.
=> Fix logging without format string

.github/workflows/scorecard.yml, README.rst
The change adds the https://github.com/ossf/scorecard-action Action.
This runs a few checkers about proper security configuration of the repo.
=> OSSF Scorecard & Badge

src/oic/extension/proof_of_possesion.py, src/oic/oauth2/message.py, src/oic/oic/__init__.py, src/oic/utils/authn/client.py, src/oic/utils/authn/ldap_member.py, src/oic/utils/authn/user.py, src/oic/utils/sdb.py
=> Fix mypy typing

oidc_example/op1/oc_server.py, oidc_example/op2/server.py, oidc_example/op3/server.py, oidc_example/rp2/rp2.py, oidc_example/rp3/rp3.py, src/oic/__init__.py, src/oic/extension/proof_of_possesion.py, src/oic/oauth2/provider.py, src/oic/oauth2/util.py, src/oic/oic/__init__.py, src/oic/oic/message.py, tests/test_http_util.py, tests/test_oauth2_consumer.py, tests/test_oauth2_message.py, tests/test_oic_consumer.py, tests/test_oic_message.py, tests/test_oic_provider.py, tests/test_webfinger.py
=> Apply new ruff format

src/oic/extension/device_flow.py, src/oic/oic/__init__.py
Device authorization endpoint is `device_authorization_endpoint` as per https://www.rfc-editor.org/rfc/rfc8628.html#section-4
---
=> Fix device flow authorization endpoint

src/oic/utils/time_util.py, tests/test_http_util.py, tests/test_oic_provider.py, tests/test_time_util.py
`datetime.utcnow()` has been deprecated since Python 3.12. We replace it by creating timezone-aware datetime instances everywhere `utcnow()` was used.
---
=> Replace deprecated `datetime.utcnow()`

src/oic/utils/userinfo/ldap_info.py
The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Migrate to modern logger interface
